"use client";
import {useEffect,useState} from "react";
type Asset={id:string;filename:string;url:string;alt:string;type:"IMAGE"|"VIDEO"|"DOCUMENT";createdAt:string};
const blank={filename:"",url:"",alt:"",type:"IMAGE" as Asset["type"]};
export default function Media(){
 const [items,setItems]=useState<Asset[]>([]),[form,setForm]=useState(blank),[open,setOpen]=useState(false),[editing,setEditing]=useState<Asset|null>(null),[filter,setFilter]=useState("ALL"),[message,setMessage]=useState("");
 async function load(){const r=await fetch("/api/admin/media");const d=await r.json();if(r.ok)setItems(d);else setMessage(d.error||"Unable to load media");}
 useEffect(()=>{load()},[]);
 async function save(e:React.FormEvent){e.preventDefault();const r=await fetch("/api/admin/media",{method:editing?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(editing?{...form,id:editing.id}:form)});const d=await r.json();if(r.ok){setMessage(editing?"Media asset updated.":"Media asset added.");setForm(blank);setEditing(null);setOpen(false);load()}else setMessage(d.error||"Could not save asset");}
 async function remove(id:string){if(!confirm("Remove this media record?"))return;const r=await fetch("/api/admin/media?id="+id,{method:"DELETE"});if(r.ok){setItems(x=>x.filter(a=>a.id!==id));setMessage("Media asset removed.")}}
 const shown=filter==="ALL"?items:items.filter(x=>x.type===filter);
 return <main className="admin-content"><div className="admin-kicker">CONTENT / MEDIA</div><div className="admin-page-title"><div><h1>Media Library</h1><p>Manage reusable images, video and documents with accessibility metadata.</p></div><button className="admin-primary" onClick={()=>setOpen(true)}>+ Add media</button></div>{message&&<div className="status-pill" style={{marginBottom:18}}>{message}</div>}<div className="media-toolbar">{["ALL","IMAGE","VIDEO","DOCUMENT"].map(x=><button key={x} className={filter===x?"active":""} onClick={()=>setFilter(x)}>{x}</button>)}</div><div className="media-library-grid">{shown.map(a=><article className="media-asset" key={a.id}>{a.type==="IMAGE"?<img src={a.url} alt={a.alt}/>:<div className="media-asset-icon">{a.type==="VIDEO"?"▶":"PDF"}</div>}<div><span>{a.type}</span><strong>{a.filename}</strong><small>{a.alt}</small></div><div className="media-asset-actions"><a href={a.url} target="_blank" rel="noreferrer">Open ↗</a><button onClick={()=>{setEditing(a);setForm({filename:a.filename,url:a.url,alt:a.alt,type:a.type});setOpen(true)}}>Edit</button><button onClick={()=>remove(a.id)}>Remove</button></div></article>)}</div>{!shown.length&&<div className="empty-state"><div className="empty-icon">↑</div><h2>No assets in this view</h2><p>Add your first reusable brand, team or campaign asset.</p></div>}{open&&<div className="modal"><form className="modal-card" onSubmit={save}><h2>{editing?"Edit media asset":"Add media asset"}</h2><label className="editor-field">Asset URL<input required type="url" value={form.url} onChange={e=>setForm({...form,url:e.target.value})}/></label><label className="editor-field">Filename<input required value={form.filename} onChange={e=>setForm({...form,filename:e.target.value})}/></label><label className="editor-field">Type<select value={form.type} onChange={e=>setForm({...form,type:e.target.value as Asset["type"]})}><option>IMAGE</option><option>VIDEO</option><option>DOCUMENT</option></select></label><label className="editor-field">Alt text<input required value={form.alt} onChange={e=>setForm({...form,alt:e.target.value})}/></label><div className="editor-actions"><button type="button" className="admin-secondary" onClick={()=>{setOpen(false);setEditing(null);setForm(blank)}}>Cancel</button><button className="admin-primary">Save asset</button></div></form></div>}</main>
}