export type DirectoryItem={id:string;kind:"team"|"partner";name:string;role?:string;category?:string;bio?:string;imageUrl?:string;logoUrl?:string;featured?:boolean;sortOrder:number};

export const legacyTeam:Omit<DirectoryItem,"id">[]=[
{name:"Ali Ahmed",role:"Founder & CEO",category:"Leadership",featured:true,sortOrder:1},
{name:"Karim Maknojia",role:"CTO",category:"Leadership",featured:true,sortOrder:2},
{name:"Shahid Ahmed",role:"Chief Operating Officer",category:"Leadership",featured:true,sortOrder:3},
{name:"Mubashir Hussain",role:"Software Development Manager",category:"Technology",sortOrder:4},
{name:"Murtaza Baig",role:"Manager SQA & System Support",category:"Technology",sortOrder:5},
{name:"Noor Muhammad",role:"Manager Infrastructure & Info Sec",category:"Technology",sortOrder:6},
{name:"Asif Lalani",role:"Manager Implementation KCBL",category:"Delivery",sortOrder:7},
{name:"Bahram Khan",role:"Manager Implementation KCBL",category:"Delivery",sortOrder:8},
{name:"Nigah E Nazar",role:"Manager Finance & Admin",category:"Operations",sortOrder:9},
{name:"Muhammad Bilal",role:"Team Lead Web UI/UX Developer",category:"Technology",sortOrder:10},
{name:"Muhammad Awais",role:"Software Engineer",category:"Technology",sortOrder:11},
{name:"Muhammad Abbas",role:"Sr. Software Engineer",category:"Technology",sortOrder:12},
{name:"Nouman Nasir",role:"Software Engineer",category:"Technology",sortOrder:13},
{name:"Naeem Ullah",role:"Software Engineer",category:"Technology",sortOrder:14},
{name:"Nasrullah Baig",role:"Assistant Manager QA and CS",category:"Quality",sortOrder:15},
{name:"Sumbal Shaheen",role:"Software QA Engineer",category:"Quality",sortOrder:16},
{name:"Akhtar Hussain",role:"Network Engineer",category:"Technology",sortOrder:17},
{name:"Shahid Khan",role:"Business Analyst",category:"Business",sortOrder:18},
{name:"Syed Zain Ali Shah",role:"Software Engineer",category:"Technology",sortOrder:19},
{name:"Muhammad Hamza",role:"Software QA Engineer",category:"Quality",sortOrder:20},
{name:"Basit Ali",role:"Software Engineer",category:"Technology",sortOrder:21},
{name:"Umair Ali",role:"Software Engineer",category:"Technology",sortOrder:22},
{name:"Ghulam Ali",role:"Software Engineer",category:"Technology",sortOrder:23},
{name:"Altaf Ali",role:"Project Coordinator",category:"Delivery",sortOrder:24},
{name:"Sawara Rehman",role:"Software Engineer — Mobile App",category:"Technology",sortOrder:25},
{name:"Beenish Zahid",role:"Software Engineer",category:"Technology",sortOrder:26},
{name:"Muqadas Fatima",role:"Software Engineer",category:"Technology",sortOrder:27},
{name:"Zeeshan Haider",role:"Customer Support Engineer",category:"Support",sortOrder:28},
{name:"Mudassar Siddiqui",role:"QA Engineer",category:"Quality",sortOrder:29},
{name:"Samrana Kafeel",role:"QA Engineer",category:"Quality",sortOrder:30},
{name:"Iqra Zainab",role:"QA Engineer",category:"Quality",sortOrder:31},
{name:"Zainab Yaqoob",role:"Software Engineer",category:"Technology",sortOrder:32},
{name:"Ali Asghar",role:"Software Engineer",category:"Technology",sortOrder:33},
{name:"Sadaqat Hussain",role:"Senior Flutter Developer",category:"Technology",sortOrder:34},
{name:"GulBadin",role:"System & Network Engineer",category:"Technology",sortOrder:35},
{name:"Zohaib Hassan",role:"UX/UI Researcher and Designer",category:"Design",sortOrder:36},
{name:"Hasan Muzaffar",role:"SQA Engineer",category:"Quality",sortOrder:37},
{name:"Junaid",role:"SQA Engineer",category:"Quality",sortOrder:38},
{name:"Atif Saleem",role:"Flutter Developer",category:"Technology",sortOrder:39},
{name:"Urooj Arif",role:"Software Engineer (Intern)",category:"Technology",sortOrder:40},
{name:"Feroz Ali Khan",role:"Office Assistant",category:"Operations",sortOrder:41},
{name:"Jahangir Khan",role:"Office Assistant",category:"Operations",sortOrder:42}
];

export const legacyPartners:Omit<DirectoryItem,"id">[]=[
{name:"Aga Khan Agency for Microfinance",category:"Financial Services",bio:"Long-standing collaboration across digital financial services and microfinance transformation.",sortOrder:1},
{name:"Aga Khan Foundation",category:"Development",bio:"Collaboration supporting technology-enabled social and economic development initiatives.",sortOrder:2},
{name:"Orange Mobile",category:"Digital Finance",bio:"Technology collaboration for digital financial services, channels and transaction capabilities.",sortOrder:3},
{name:"The First Microfinance Bank",category:"Banking",bio:"Core banking, mobile and digital finance implementation experience across multiple markets.",sortOrder:4},
{name:"SyriaTel",category:"Telecommunications",bio:"Technology and digital channel collaboration referenced in MFSYS implementation history.",sortOrder:5},
{name:"KCBL",category:"Banking",bio:"Implementation and delivery experience for banking technology and digital transformation.",sortOrder:6}
];
