export type Product={
  name:string;eyebrow:string;tagline:string;description:string;
  capabilities:string[];outcomes:string[];architecture:string[];href:string
};
export const productData:Product[]=[
 {name:"CiiHive",eyebrow:"DIGITAL CORE BANKING",tagline:"AI-native banking infrastructure for inclusive growth.",description:"A cloud-native, microservices-based digital core banking platform designed for modern financial institutions, with intelligence embedded across the customer and lending lifecycle.",capabilities:["Digital onboarding & KYC","Core banking & account management","Mobile and digital banking","AI credit scoring & decision support","Loan management and servicing","IFRS 9 integration","200+ operational and regulatory reports","API-first integration architecture"],outcomes:["Faster product launch","Lower operational complexity","Better credit decisions","Scalable digital channels"],architecture:["Cloud-native","Microservices","API-first","AWS / GCP ready","Secure multi-tenant SaaS"],href:"/products/ciihive"},
 {name:"LoanLeaf",eyebrow:"DIGITAL LOAN ORIGINATION",tagline:"From application to decision, intelligently.",description:"A configurable loan origination platform that digitizes application, verification, credit assessment, approval and disbursement workflows.",capabilities:["Digital application","Document & identity verification","Workflow orchestration","Credit assessment","Approval rules","Disbursement integration"],outcomes:["Shorter turnaround time","Consistent decisions","Better applicant experience","Reduced manual work"],architecture:["API-first","Workflow-driven","Cloud-ready"],href:"/products/loanleaf"},
 {name:"Smart Mudarabah",eyebrow:"ISLAMIC FINANCE",tagline:"Digital Mudarabah management, end to end.",description:"An end-to-end digital platform for structuring, managing, monitoring and reporting Mudarabah-based financing.",capabilities:["Mudarabah onboarding","Investment & financing lifecycle","Profit allocation","Shariah-aligned workflows","Portfolio monitoring","Reporting"],outcomes:["Operational transparency","Consistent governance","Scalable Islamic finance operations"],architecture:["Modular","API-first","Enterprise-ready"],href:"/products/smart-mudarabah"},
 {name:"DigitalKisaan",eyebrow:"AGRI FINANCE",tagline:"Digital infrastructure for farmers and value chains.",description:"A digital platform connecting farmers, cooperatives, finance and agricultural ecosystems.",capabilities:["Farmer registration","Cooperative management","Finance workflows","Value-chain data","Field operations","Monitoring & reporting"],outcomes:["Greater financial access","Better visibility","Stronger value-chain coordination"],architecture:["Mobile-first","Cloud-ready","Offline-capable"],href:"/products/digitalkisaan"},
 {name:"LoanIQ",eyebrow:"CREDIT INTELLIGENCE",tagline:"Intelligence for better lending decisions.",description:"AI-enabled lending intelligence supporting risk assessment, decisioning and portfolio insight.",capabilities:["AI credit scoring","Risk segmentation","Decision support","Predictive analytics","Portfolio intelligence"],outcomes:["Improved risk assessment","Faster decisions","More consistent lending"],architecture:["AI-ready","API-first","Explainable decision support"],href:"/products/loaniq"},
 {name:"Zaroraat24",eyebrow:"DIGITAL SERVICES",tagline:"Making essential financial services more accessible.",description:"A digital experience designed to connect customers with essential financial products and services.",capabilities:["Digital customer journey","Product discovery","Application workflows","Notifications","Partner integrations"],outcomes:["Improved accessibility","Simpler customer journeys","Digital reach"],architecture:["Mobile-first","API-enabled"],href:"/products/zaroraat24"},
 {name:"XchangeCarbon",eyebrow:"CLIMATE & CARBON",tagline:"Digital infrastructure for the carbon economy.",description:"A digital carbon ecosystem connecting green projects, MRV, carbon-credit computation and marketplace participants.",capabilities:["Green project registration","MRV workflows","Carbon-credit computation","Marketplace","Smart contracts","Impact reporting"],outcomes:["Transparent carbon transactions","Better project visibility","Measurable climate impact"],architecture:["Blockchain-enabled","Cloud-native","Marketplace architecture"],href:"/products/xchangecarbon"},
 {name:"CargoGuard",eyebrow:"LOGISTICS TECHNOLOGY",tagline:"Visibility, trust and control across freight.",description:"A SaaS logistics platform for load booking, dispatch, tracking, proof of delivery and driver compliance.",capabilities:["Load booking","Dispatch","GPS tracking","Proof of delivery","Driver KYC","Geofencing","Anti-spoofing","DOT / MC verification"],outcomes:["Real-time visibility","Reduced operational risk","Better carrier compliance","Faster exception management"],architecture:["SaaS","Mobile-first","Real-time location","API-enabled"],href:"/products/cargoguard"},
 {name:"IFRS9 Impairment Solution",eyebrow:"RISK & REGULATORY TECHNOLOGY",tagline:"Practical intelligence for expected credit loss.",description:"An impairment platform supporting PD, LGD, lifetime estimation and expected credit loss calculations for IFRS 9.",capabilities:["PD estimation","LGD estimation","Lifetime estimation","ECL calculation","Scenario analysis","Regulatory reporting"],outcomes:["Consistent impairment methodology","Faster calculation cycles","Stronger auditability"],architecture:["Analytics-ready","Enterprise reporting","API-enabled"],href:"/products/ifrs9"}
];
